name: "build"
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        operatingSystem: [ 'macOS-latest', 'ubuntu-18.04' ]

    runs-on: ${{ matrix.operatingSystem }}
    timeout-minutes: 30
    steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Setup Deps (macOS)
          if: matrix.operatingSystem == 'macOS-latest'
          run: |
              ln -ffs /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib /usr/local/lib/
              ln -ffs /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib /usr/local/lib/
              ln -ffs /usr/local/opt/openssl@1.1/lib/pkgconfig/* /usr/local/lib/pkgconfig/
              ln -ffs /usr/local/opt/openssl@1.1/include/* /usr/local/include/
              brew install automake
        - run: |
            git submodule update --init
            cd libplist
            ./autogen.sh
            make -j8
            sudo make install
        - name: Configure ldid
          run: cmake -B build -DLDID_STATIC=NO
        - name: Compile ldid
          run: cmake --build build
        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
           name: ${{ matrix.operatingSystem }}.ldid
           path: build/ldid

  static-build:
    strategy:
      matrix:
        operatingSystem: [ 'macOS-latest', 'ubuntu-18.04' ]

    runs-on: ${{ matrix.operatingSystem }}
    timeout-minutes: 30
    steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Setup Deps (macOS)
          if: matrix.operatingSystem == 'macOS-latest'
          run: |
              ln -ffs /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib /usr/local/lib/
              ln -ffs /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib /usr/local/lib/
              ln -ffs /usr/local/opt/openssl@1.1/lib/pkgconfig/* /usr/local/lib/pkgconfig/
              ln -ffs /usr/local/opt/openssl@1.1/include/* /usr/local/include/
              brew install automake
        - name: Build libplist
          run: |
            git submodule update --init
            cd libplist
            ./autogen.sh
            make -j8
            sudo make install
        - name: Configure ldid
          run: cmake -B build -DLDID_STATIC=YES
        - name: Compile ldid
          run: cmake --build build
        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
           name: ${{ matrix.operatingSystem }}.static.ldid
           path: build/ldid
